### ISSUE TITLE
Improve performance on multi-core machines

### ISSUE THREAD

**Issue by Giszmo** [pioug/gulp-html-minifier-terser#2]
As far as I can see, html-minifier-terser is inherently dealing with one file at a time and there is not much potential for multithreading but gulp-html-minifier-terser works on many files, each of which needs minification independently of other files.

I need to minify over 800 files in each run and it takes 4 minutes on my 24 core machine. How can I make it run on multiple cores?

**Comment by Giszmo** [comment]
I'm getting close but gulp confuses me. How do I now actually run and not only instantiate the minifier?

```
const htmlmin = require('gulp-html-minifier-terser');
const transform = require('parallel-transform');

gulp.task("minify", () => {
  return gulp
    .src("_site/**/*.html")
    .pipe(
      transform(24, (file, callback) => {
        htmlmin({
          collapseWhitespace: true,
          removeComments: true,
          minifyCSS: true,
          minifyJS: true,
        })
        callback(null, file)
      })
    )
    .pipe(gulp.dest("_site"));
});
```

**Comment by pioug** [comment]
I am not sure `parallel-transform` uses multiple threads actually. Maybe try https://www.npmjs.com/package/gulp-multi-thread-task or https://www.npmjs.com/package/gulp-multi-process.

But in all cases, the plugin `gulp-html-minifier-terser` is designed to process one file at a time and this can't be changed.

**Comment by Giszmo** [comment]
But ... don't you care about it being used? It's fine that it's designed for one file at a time but the usage instructions could contain how to run multiple processes for multiple files to not waste 20x the time.

**Comment by pioug** [comment]
I don't think it's a good idea to solve this problem within the scope of this plugin. Sorry but I don't want to investigate it.
